// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAPpGahWksPmsEK2E915mXBxPqZmNeeeY',
    appId: '1:672956059765:web:321e7479db6383ca34e83c',
    messagingSenderId: '672956059765',
    projectId: 'organiz-em',
    authDomain: 'organiz-em.firebaseapp.com',
    storageBucket: 'organiz-em.appspot.com',
    measurementId: 'G-JTZM7EXQLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwa06699Nso386DaOGBK8RNcQ7MtbArWU',
    appId: '1:672956059765:android:f58da56f388e6af834e83c',
    messagingSenderId: '672956059765',
    projectId: 'organiz-em',
    storageBucket: 'organiz-em.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Ey3pY7dkwGxhvwHrOF2GRg5nbZknTXA',
    appId: '1:672956059765:ios:e7bd2076233238f434e83c',
    messagingSenderId: '672956059765',
    projectId: 'organiz-em',
    storageBucket: 'organiz-em.appspot.com',
    iosBundleId: 'com.example.todo',
  );
}
